#!/usr/bin/env python
r'''
This program is the form "action" taken by the "newdata.html", which,
as its name suggests, allows the user to enter new records into the
database.

So this program gets called by the "newdata.py," which itself
is a program to display an entry page for new records. It enters records
through a form in the html code generated by "newdata.py".

The form's "action" program, to be called when they press "Submit,"
is this program, currently (October 21, 2024 1:00 PM) called "test3.py".
I'll give it a real name soon.

It gathers the data they entered into a "file record," the way I have it
now it has 8 fields: Numeric ID, Short Description, Long Description,
Location (coded by a two-letter code), Modified Date, Owner, Comments,
and Date Created.

I used to keep each record in a dataclass object;
now I keep them in a named tuple. I really didn't need the class
structure.
'''

# Updated: Monday, October 21, 2024 13:00:00.

_author_ = "Bryan A. Zimmer"
_with_help_from_ = "Kevin R. Baumgarten"
_date_of_this_notation_ = "10/21/2024"

_project_name_ = "dkfiles"


import os
import sys
import sqlite3
import mycgi
from MyFile import *


# The "w" stands for a filehandle.write() method. It writes to a standard
# debug file named after each program (e.g. test3_debug.txt)

w('\nTHE PROGRAM STARTS HERE:\n')
form = mycgi.Form()
w(f'{form=}\n')

def getformdata():
    global form
    w(f'Retrieving form data...\n')
    if form:
       fileid = form.getvalue('fileid')
       w('we got a form\n')
    else:
       w('We didn\'t even get a form!\n')
    fileid = form.getvalue('fileid')
    w(f'Got the value of fileid as {fileid}.\n')
    w(f'\n{fileid = }\n')
    w(f'type of fileid is {type(fileid)}.\n')
    w(f'{fileid = }\n')
    sd = sqlized(form.getvalue('shortdesc'))    
    ld = sqlized(form.getvalue('longdesc'))
    w(f'{sd = }\n{ld = }\n')
    lo = form.getvalue('location')
    location = locations['lo']
    dt = ''
    cr = sqldate() # Date stamps it right at this very moment.
    comments=sqlized(form.getvalue('comments'))
    owner = sqlized(form.getvalue('owner'))
    mytup = (fileid,sd,ld,lo,dt,owner,comments,cr)
    myrec = onefile._make(mytup) # "onefile", and a lot of utility
    w(f'{myrec = }\n')           # stuff are in the MyFile.py module.
    return myrec
    
def store_rec_in_database(onerec):
    w('...in store_rec....\n')
    w(f'onerec is {onerec}\n')
    con = sqlite3.connect(db)
    cur = con.cursor()
    sql = f'''INSERT INTO newfiles VALUES({onerec.fileid},'{onerec.sd}','{onerec.ld}','{onerec.lo}','{onerec.dt}','{onerec.owner}','{onerec.comments}','{onerec.cr}') '''
    w(f'{sql=}')
    cur.execute(sql)
    con.commit()
    con.close()

def make_display_page(onerec):
    # create a page string
    w(f'{onerec.fileid=},{onerec.sd=},{onerec.ld=}\n{onerec.lo=},' \
      f'{onerec.owner=},{onerec.comments=},{onerec.cr=}\n')
    
    page = f'''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><link rel="stylesheet" href="/css/entry.css" /><style></style></head>''' \
        f'''<body><h3> Here are the form fields:</h3><br /><b><ul><li>fileid: {onerec.fileid}</li><li>shortdesc: {onerec.sd}</li><li>longdesc: {onerec.ld}</li>''' \
        f'''<li>location: {locations[onerec.lo]}</li><li>Owner: {onerec.owner}</li><li>Created: {onerec.cr}</li></ul></b>''' \
        f'''<br /><h5>That&apos;s what this program thinks of &quot;newdata.py&quot;</h5><br />''' \
        f'''<div name="copy">''' \
        f'''<div name="copy-text">''' \
        f'''<p>&copy;Kevin R. Baumgarten, 2024. All rights reserved.</p></div></div>''' \
        f'''</body></html>'''
    w(f'{page = }\n')
    return page


def display_page(page: str) -> int:
    
    w('displaying page...\n')
    print('Content-type: text/html\n\n')
    print(page)
    print()
    return 0

 
def main() -> int:
    w('...in main()...\n')
    onerec = getformdata()
    w(f'\n\n{onerec = }\n\n')
    store_rec_in_database(onerec)
    page=make_display_page(onerec)
    w('\nWe\'re going to display the page')
    rv = display_page(page)
    return rv

if __name__ == '__main__':
    w(f'Executing {prog} on {today} at {now()}.\n')
    main()

